GRANT SELECT ON `test`.`squad_rank_name` TO 'dayzserver'@'%1';
GRANT SELECT, INSERT, UPDATE, DELETE ON `test`.`squad_rank` TO 'dayzserver'@'%1';
GRANT SELECT, INSERT, UPDATE, DELETE ON `test`.`squad` TO 'dayzserver'@'%1';
GRANT SELECT ON `test`.`server_ip` TO 'dayzserver'@'%1';
GRANT SELECT ON `test`.`server_instance` TO 'dayzserver'@'%1';
GRANT SELECT ON `test`.`quest` TO 'dayzserver'@'%1';
GRANT SELECT, INSERT, UPDATE, DELETE ON `test`.`player_login` TO 'dayzserver'@'%1';
GRANT SELECT, INSERT, UPDATE, DELETE ON `test`.`player_data` TO 'dayzserver'@'%1';
GRANT SELECT ON `test`.`object_spawns` TO 'dayzserver'@'%1';
GRANT SELECT, INSERT, UPDATE, DELETE ON `test`.`object_data` TO 'dayzserver'@'%1';
GRANT SELECT ON `test`.`object_classes` TO 'dayzserver'@'%1';
GRANT SELECT, INSERT, UPDATE, DELETE ON `test`.`message` TO 'dayzserver'@'%1';
GRANT SELECT, INSERT, UPDATE, DELETE ON `test`.`instance_state` TO 'dayzserver'@'%1';
GRANT SELECT, INSERT, UPDATE, DELETE ON `test`.`instance_squad` TO 'dayzserver'@'%1';
GRANT SELECT, INSERT, UPDATE, DELETE ON `test`.`instance_garage` TO 'dayzserver'@'%1';
GRANT SELECT, INSERT, UPDATE, DELETE ON `test`.`instance_building` TO 'dayzserver'@'%1';
GRANT SELECT ON `test`.`global_state` TO 'dayzserver'@'%1';
GRANT SELECT ON `test`.`cust_loadout_profile` TO 'dayzserver'@'%1';
GRANT SELECT ON `test`.`cust_loadout` TO 'dayzserver'@'%1';
GRANT SELECT, INSERT, UPDATE, DELETE ON `test`.`character_data` TO 'dayzserver'@'%1';
GRANT SELECT ON `test`.`building` TO 'dayzserver'@'%1';
GRANT INSERT ON `test`.`instance_movement` TO 'dayzserver'@'%1';