// config.bin - 20:42:33 07/02/13, generated in 0.02 seconds
// Generated by unRap v1.06 by Kegetys
// Separate rootclasses: Disabled, Automatic comments: Enabled

#define private		0
#define protected		1
#define public		2

#define TEast		0
#define TWest		1
#define TGuerrila		2
#define TCivilian		3
#define TSideUnknown		4
#define TEnemy		5
#define TFriendly		6
#define TLogic		7

#define true	1
#define false	0

class CfgPatches {
	class KPFS_UAZ451 {
		units[] = {"kpfs_uaz451", "kpfs_uaz451_lm"};
		requiredVersion = 1.62;
		requiredAddons[] = {"CACharacters", "CAWheeled", "CAWheeled_E"};
	};
};
class Reflectors;	// External class reference
class Right;	// External class reference
class Left;	// External class reference

class CfgVehicles {
	class UAZ_Unarmed_Base;	// External class reference
	
	class kpfs_uaz451 : UAZ_Unarmed_Base {
		faction = CIV;
		wheelCircumference = 2.02;
		scope = public;
		side = TCivilian;
		crew = "Citizen1";
		displayName = $STR_KPFS_UAZ451;
		model = "\kpfs_uaz451\uaz451";
		DriverAction = "Skodovka_Driver";
		cargoAction[] = {"UAZ_Cargo01", "UAZ_Cargo01", "UAZ_Cargo01", "UAZ_Cargo01"};
		typicalCargo[] = {"Citizen1"};
		
		class TransportMagazines {};
		transportSoldier = 5;
		Icon = "\kpfs_uaz451\data\ico\icomap_van_ca.paa";
		picture = "\ca\wheeled_e\data\UI\Picture_s1203_CA.paa";
		outsideSoundFilter = 1;
		insideSoundCoef = 0.85;
		terrainCoef = 3.0;
		turnCoef = 2;
		steerAheadPlan = 0.15;
		
		// threat (VSoft, VArmor, VAir), how threatening vehicle is to unit types
		threat[] = {0.0, 0.0, 0.0};

		weapons[] = {"CarHorn"};
		soundGear[] = {"", 5.62341e-005, 1};
		soundGetIn[] = {"\ca\Sounds_E\Wheeled_E\lada\lada_door", db0, 1};
		soundGetOut[] = {"\ca\Sounds_E\Wheeled_E\lada\lada_door", db0, 1, 30};
		soundEngineOnInt[] = {"\ca\Sounds_E\Wheeled_E\lada\lada_int_start", 1.0, 1.0};
		soundEngineOnExt[] = {"\ca\Sounds_E\Wheeled_E\lada\lada_ext_start", 1.0, 1.0, 100};
		soundEngineOffInt[] = {"\ca\Sounds_E\Wheeled_E\lada\lada_int_stop", 1.0, 1.0};
		soundEngineOffExt[] = {"\ca\Sounds_E\Wheeled_E\lada\lada_ext_stop", 1.0, 1.0, 100};
		buildCrash0[] = {"Ca\sounds\Vehicles\Crash\tank_building_01", 0.707946, 1, 150};
		buildCrash1[] = {"Ca\sounds\Vehicles\Crash\tank_building_02", 0.707946, 1, 150};
		buildCrash2[] = {"Ca\sounds\Vehicles\Crash\tank_building_03", 0.707946, 1, 150};
		buildCrash3[] = {"Ca\sounds\Vehicles\Crash\tank_building_04", 0.707946, 1, 150};
		soundBuildingCrash[] = {"buildCrash0", 0.25, "buildCrash1", 0.25, "buildCrash2", 0.25, "buildCrash3", 0.25};
		WoodCrash0[] = {"Ca\sounds\Vehicles\Crash\tank_wood_01", 0.707946, 1, 150};
		WoodCrash1[] = {"Ca\sounds\Vehicles\Crash\tank_wood_02", 0.707946, 1, 150};
		WoodCrash2[] = {"Ca\sounds\Vehicles\Crash\tank_wood_03", 0.707946, 1, 150};
		WoodCrash3[] = {"Ca\sounds\Vehicles\Crash\tank_wood_04", 0.707946, 1, 150};
		soundWoodCrash[] = {"woodCrash0", 0.25, "woodCrash1", 0.25, "woodCrash2", 0.25, "woodCrash3", 0.25};
		ArmorCrash0[] = {"Ca\sounds\Vehicles\Crash\tank_vehicle_01", 0.707946, 1, 150};
		ArmorCrash1[] = {"Ca\sounds\Vehicles\Crash\tank_vehicle_02", 0.707946, 1, 150};
		ArmorCrash2[] = {"Ca\sounds\Vehicles\Crash\tank_vehicle_03", 0.707946, 1, 150};
		ArmorCrash3[] = {"Ca\sounds\Vehicles\Crash\tank_vehicle_04", 0.707946, 1, 150};
		soundArmorCrash[] = {"ArmorCrash0", 0.25, "ArmorCrash1", 0.25, "ArmorCrash2", 0.25, "ArmorCrash3", 0.25};
		damageResistance = 0.01511;
		cost = 3000;
		fuelCapacity = 60;
		armor = 20;
		
		class Library {
			libTextDesc = "UAZ-451/3909";
		};
		rarityUrban = 0.9;
		
		class Damage {
			tex[] = {};
			mat[] = {"kpfs_uaz451\data\detailmapy\uaz451.rvmat", "kpfs_uaz451\data\detailmapy\uaz451_damage.rvmat", "kpfs_uaz451\data\detailmapy\uaz451_destruct.rvmat", "kpfs_uaz451\data\detailmapy\uaz_main_metal.rvmat", "kpfs_uaz451\data\detailmapy\uaz_main_metal.rvmat", "kpfs_uaz451\data\detailmapy\uaz_main_metal_destruct.rvmat", "kpfs_uaz451\data\detailmapy\uaz_other_metal.rvmat", "kpfs_uaz451\data\detailmapy\uaz_other_metal.rvmat", "kpfs_uaz451\data\detailmapy\uaz_other_metal_destruct.rvmat", "kpfs_uaz451\data\detailmapy\s1203_glass.rvmat", "kpfs_uaz451\data\detailmapy\s1203_glass_damage.rvmat", "kpfs_uaz451\data\detailmapy\s1203_glass_damage.rvmat", "kpfs_uaz451\data\detailmapy\s1203_glass_in.rvmat", "kpfs_uaz451\data\detailmapy\s1203_glass_in_damage.rvmat", "kpfs_uaz451\data\detailmapy\s1203_glass_in_damage.rvmat"};
		};
		
		class AnimationSources {
			class HitLFWheel {
				source = "Hit";
				hitpoint = "HitLFWheel";
				raw = 1;
			};
			
			class HitRFWheel : HitLFWheel {
				hitpoint = "HitRFWheel";
			};
			
			class HitLBWheel : HitLFWheel {
				hitpoint = "HitLBWheel";
			};
			
			class HitRBWheel : HitLFWheel {
				hitpoint = "HitRBWheel";
			};
			
			class HitLF2Wheel : HitLFWheel {
				hitpoint = "HitLF2Wheel";
			};
			
			class HitRF2Wheel : HitLFWheel {
				hitpoint = "HitRF2Wheel";
			};
			
			class HitLMWheel : HitLFWheel {
				hitpoint = "HitLMWheel";
			};
			
			class HitRMWheel : HitLFWheel {
				hitpoint = "HitRMWheel";
			};
			
			class HitGlass1 {
				source = "Hit";
				hitpoint = "HitGlass1";
				raw = 1;
			};
			
			class HitGlass2 : HitGlass1 {
				hitpoint = "HitGlass2";
			};
			
			class HitGlass3 : HitGlass1 {
				hitpoint = "HitGlass3";
			};
			
			class HitGlass4 : HitGlass1 {
				hitpoint = "HitGlass4";
			};
			
			class HitGlass5 : HitGlass1 {
				hitpoint = "HitGlass5";
			};
			
			class HitGlass6 : HitGlass1 {
				hitpoint = "HitGlass6";
			};
			
			class HitGlass7 : HitGlass1 {
				hitpoint = "HitGlass7";
			};
			
			class HitGlass8 : HitGlass1 {
				hitpoint = "HitGlass8";
			};
			
			class HitGlass9 : HitGlass1 {
				hitpoint = "HitGlass9";
			};
			
			class HitGlass10 : HitGlass1 {
				hitpoint = "HitGlass10";
			};
			
			class HitGlass11 : HitGlass1 {
				hitpoint = "HitGlass11";
			};
			
			class HitGlass12 : HitGlass1 {
				hitpoint = "HitGlass12";
			};
		};
		
		class HitPoints {
			class HitGlass1 {
				armor = 0.1;
				material = -1;
				name = "sklo_p";
				visual = "sklo_p";
				passThrough = false;
			};
			
			class HitGlass2 : HitGlass1 {
				name = "sklo_p1";
				visual = "sklo_p1";
			};
			
			class HitGlass3 : HitGlass1 {
				name = "sklo_p2";
				visual = "sklo_p2";
			};
			
			class HitGlass4 : HitGlass1 {
				name = "sklo_p3";
				visual = "sklo_p3";
			};
			
			class HitGlass5 : HitGlass1 {
				name = "sklo_l1";
				visual = "sklo_l1";
			};
			
			class HitGlass6 : HitGlass1 {
				name = "sklo_l2";
				visual = "sklo_l3";
			};
			
			class HitGlass7 : HitGlass1 {
				name = "sklo_l3";
				visual = "glass3";
			};
			
			class HitGlass8 : HitGlass1 {
				name = "sklo_z";
				visual = "sklo_z";
			};
			
			class HitGlass9 : HitGlass1 {
				name = "sklo_pp";
				visual = "sklo_pp";
			};
			
			class HitGlass10 : HitGlass1 {
				name = "sklo_pl";
				visual = "sklo_pl";
			};
			
			class HitGlass11 : HitGlass1 {
				name = "sklo_p4";
				visual = "sklo_p4";
			};
			
			class HitGlass12 : HitGlass1 {
				name = "sklo_l4";
				visual = "sklo_l4";
			};
			
			class HitLFWheel {
				armor = 0.25;
				material = -1;
				name = "levy predni tlumic";
				visual = "";
				passThrough = 0.2;
			};
			
			class HitLBWheel : HitLFWheel {
				name = "levy zadni tlumic";
				visual = "";
			};
			
			class HitRFWheel : HitLFWheel {
				name = "pravy predni tlumic";
				visual = "";
			};
			
			class HitRBWheel : HitLFWheel {
				name = "pravy zadni tlumic";
				visual = "";
			};
			
			class HitLF2Wheel : HitLFWheel {
				name = "levy dalsi tlumic";
				visual = "";
			};
			
			class HitRF2Wheel : HitLFWheel {
				name = "pravy dalsi tlumic";
				visual = "";
			};
			
			class HitLMWheel : HitLFWheel {
				name = "levy prostredni tlumic";
				visual = "";
			};
			
			class HitRMWheel : HitLFWheel {
				name = "pravy prostredni tlumic";
				visual = "";
			};
		};
		hiddenSelections[] = {"Camo01"};
		hiddenSelectionsTextures[] = {"\kpfs_uaz451\civil\uaz451.paa"};
	};
	
	class kpfs_uaz451_light_blue : kpfs_uaz451 {
		scope = public;
		crew = "RU_Worker2";
		displayName = $STR_KPFS_UAZ451_LIGHT_BLUE;
		hiddenSelections[] = {"Camo01"};
		hiddenSelectionsTextures[] = {"\kpfs_uaz451\civil\uaz451_light_blue.paa"};
	};
	
	class kpfs_uaz451_blue : kpfs_uaz451 {
		scope = public;
		crew = "Profiteer2";
		displayName = $STR_KPFS_UAZ451_BLUE;
		hiddenSelections[] = {"Camo01"};
		hiddenSelectionsTextures[] = {"\kpfs_uaz451\civil\uaz451_blue.paa"};
	};
	
	class kpfs_uaz451_red : kpfs_uaz451 {
		scope = public;
		crew = "Citizen3";
		displayName = $STR_KPFS_UAZ451_RED;
		hiddenSelections[] = {"Camo01"};
		hiddenSelectionsTextures[] = {"\kpfs_uaz451\civil\uaz451_red.paa"};
	};
	
	class kpfs_uaz451_green : kpfs_uaz451 {
		scope = public;
		crew = "Woodlander1";
		displayName = $STR_KPFS_UAZ451_GREEN;
		hiddenSelections[] = {"Camo01"};
		hiddenSelectionsTextures[] = {"\kpfs_uaz451\civil\uaz451_green.paa"};
	};
	
	class kpfs_uaz451_yellow : kpfs_uaz451 {
		scope = public;
		crew = "Citizen4";
		displayName = $STR_KPFS_UAZ451_YELLOW;
		hiddenSelections[] = {"Camo01"};
		hiddenSelectionsTextures[] = {"\kpfs_uaz451\civil\uaz451_yellow.paa"};
	};
	
	class kpfs_uaz451_grey : kpfs_uaz451 {
		scope = public;
		crew = "Villager1";
		displayName = $STR_KPFS_UAZ451_GREY;
		hiddenSelections[] = {"Camo01"};
		hiddenSelectionsTextures[] = {"\kpfs_uaz451\civil\uaz451_grey.paa"};
	};
	
	class kpfs_uaz451_black : kpfs_uaz451 {
		scope = public;
		crew = "Rocker1";
		displayName = $STR_KPFS_UAZ451_BLACK;
		hiddenSelections[] = {"Camo01"};
		hiddenSelectionsTextures[] = {"\kpfs_uaz451\civil\uaz451_black.paa"};
	};
	
	class kpfs_uaz451_pink : kpfs_uaz451 {
		scope = public;
		crew = "Rocker2";
		displayName = $STR_KPFS_UAZ451_PINK;
		hiddenSelections[] = {"Camo01"};
		hiddenSelectionsTextures[] = {"\kpfs_uaz451\civil\uaz451_pink.paa"};
	};
	
	class kpfs_uaz451_aeroflot : kpfs_uaz451 {
		scope = public;
		crew = "Assistant";
		displayName = $STR_KPFS_UAZ451_AEROFLOT;
		hiddenSelections[] = {"Camo01"};
		hiddenSelectionsTextures[] = {"\kpfs_uaz451\civil\uaz451_aeroflot.paa"};
	};
	
	class kpfs_uaz451_cdf : kpfs_uaz451 {
		faction = CDF;
		crew = "CDF_Soldier_Officer";
		hiddenSelections[] = {"Camo01"};
		hiddenSelectionsTextures[] = {"\kpfs_uaz451\army\uaz451_cdf.paa"};
	};
	
	class kpfs_uaz451_ins : kpfs_uaz451 {
		faction = INS;
		crew = "Ins_Commander";
		hiddenSelections[] = {"Camo01"};
		hiddenSelectionsTextures[] = {"\kpfs_uaz451\army\uaz451_ins.paa"};
	};
	
	class kpfs_uaz451_gue : kpfs_uaz451 {
		faction = GUE;
		crew = "GUE_Commander";
		hiddenSelections[] = {"Camo01"};
		hiddenSelectionsTextures[] = {"\kpfs_uaz451\army\uaz451_gue.paa"};
	};
	
	class kpfs_uaz451_tk : kpfs_uaz451 {
		faction = BIS_TK;
		crew = "GUE_Commander";
		hiddenSelections[] = {"Camo01"};
		hiddenSelectionsTextures[] = {"\kpfs_uaz451\army\uaz451_tk.paa"};
	};
	
	class kpfs_uaz451_tk_ins : kpfs_uaz451 {
		faction = BIS_TK_INS;
		crew = "TK_INS_Warlord_EP1";
		hiddenSelections[] = {"Camo01"};
		hiddenSelectionsTextures[] = {"\kpfs_uaz451\army\uaz451_gue.paa"};
	};
	
	class kpfs_uaz451_un : kpfs_uaz451 {
		faction = BIS_UN;
		crew = "UN_CDF_Soldier_Officer_EP1";
		hiddenSelections[] = {"Camo01"};
		hiddenSelectionsTextures[] = {"\kpfs_uaz451\army\uaz451_un.paa"};
	};
	
	class kpfs_uaz451_cz : kpfs_uaz451 {
		faction = BIS_CZ;
		crew = "CZ_Soldier_Officer_Wdl_ACR";
		hiddenSelections[] = {"Camo01"};
		hiddenSelectionsTextures[] = {"\kpfs_uaz451\army\uaz451_cz.paa"};
	};
	
	class kpfs_uaz451_lm : kpfs_uaz451 {
		scope = public;
		wheelCircumference = 2.02;
		displayName = $STR_KPFS_UAZ451_LM;
		model = "\kpfs_uaz451\uaz451_lm";
		Icon = "\kpfs_uaz451\data\ico\icomap_van_lm_ca.paa";
		crew = "Policeman";
		
		class Reflectors : Reflectors {
			class Left : Left {};
			
			class Right : Right {};
			
			class Majak1 {
				color[] = {0.1, 0.2, 0.8, 1.0};
				ambient[] = {0.01, 0.01, 0.1, 1.0};
				position = "majak light 1 start";
				direction = "majak light 1 end";
				hitpoint = "";
				selection = "majak";
				size = 0.5;
				brightness = 0.5;
			};
			
			class Majak2 : Majak1 {
				position = "majak light 2 start";
				direction = "majak light 2 end";
				hitpoint = "";
				selection = "majak";
			};
		};
		rarityUrban = 0.9;
		
		class Damage {
			tex[] = {};
			mat[] = {"kpfs_uaz451\data\detailmapy\uaz451.rvmat", "kpfs_uaz451\data\detailmapy\uaz451_damage.rvmat", "kpfs_uaz451\data\detailmapy\uaz451_destruct.rvmat", "kpfs_uaz451\data\detailmapy\uaz_main_metal.rvmat", "kpfs_uaz451\data\detailmapy\uaz_main_metal.rvmat", "kpfs_uaz451\data\detailmapy\uaz_main_metal_destruct.rvmat", "kpfs_uaz451\data\detailmapy\uaz_other_metal.rvmat", "kpfs_uaz451\data\detailmapy\uaz_other_metal.rvmat", "kpfs_uaz451\data\detailmapy\uaz_other_metal_destruct.rvmat", "kpfs_uaz451\data\detailmapy\s1203_glass.rvmat", "kpfs_uaz451\data\detailmapy\s1203_glass_damage.rvmat", "kpfs_uaz451\data\detailmapy\s1203_glass_damage.rvmat", "kpfs_uaz451\data\detailmapy\s1203_glass_in.rvmat", "kpfs_uaz451\data\detailmapy\s1203_glass_in_damage.rvmat", "kpfs_uaz451\data\detailmapy\s1203_glass_in_damage.rvmat"};
		};
		
		class AnimationSources {
			class HitLFWheel {
				source = "Hit";
				hitpoint = "HitLFWheel";
				raw = 1;
			};
			
			class HitRFWheel : HitLFWheel {
				hitpoint = "HitRFWheel";
			};
			
			class HitLBWheel : HitLFWheel {
				hitpoint = "HitLBWheel";
			};
			
			class HitRBWheel : HitLFWheel {
				hitpoint = "HitRBWheel";
			};
			
			class HitLF2Wheel : HitLFWheel {
				hitpoint = "HitLF2Wheel";
			};
			
			class HitRF2Wheel : HitLFWheel {
				hitpoint = "HitRF2Wheel";
			};
			
			class HitLMWheel : HitLFWheel {
				hitpoint = "HitLMWheel";
			};
			
			class HitRMWheel : HitLFWheel {
				hitpoint = "HitRMWheel";
			};
			
			class HitGlass1 {
				source = "Hit";
				hitpoint = "HitGlass1";
				raw = 1;
			};
			
			class HitGlass2 : HitGlass1 {
				hitpoint = "HitGlass2";
			};
			
			class HitGlass3 : HitGlass1 {
				hitpoint = "HitGlass3";
			};
			
			class HitGlass4 : HitGlass1 {
				hitpoint = "HitGlass4";
			};
			
			class HitGlass5 : HitGlass1 {
				hitpoint = "HitGlass5";
			};
			
			class HitGlass6 : HitGlass1 {
				hitpoint = "HitGlass6";
			};
			
			class HitGlass7 : HitGlass1 {
				hitpoint = "HitGlass7";
			};
			
			class HitGlass8 : HitGlass1 {
				hitpoint = "HitGlass8";
			};
			
			class HitGlass9 : HitGlass1 {
				hitpoint = "HitGlass9";
			};
			
			class HitGlass10 : HitGlass1 {
				hitpoint = "HitGlass10";
			};
			
			class HitGlass11 : HitGlass1 {
				hitpoint = "HitGlass11";
			};
			
			class HitGlass12 : HitGlass1 {
				hitpoint = "HitGlass12";
			};
		};
		
		class HitPoints {
			class HitGlass1 {
				armor = 0.1;
				material = -1;
				name = "sklo_p";
				visual = "sklo_p";
				passThrough = false;
			};
			
			class HitGlass2 : HitGlass1 {
				name = "sklo_p1";
				visual = "sklo_p1";
			};
			
			class HitGlass3 : HitGlass1 {
				name = "sklo_p2";
				visual = "sklo_p2";
			};
			
			class HitGlass4 : HitGlass1 {
				name = "sklo_p3";
				visual = "sklo_p3";
			};
			
			class HitGlass5 : HitGlass1 {
				name = "sklo_l1";
				visual = "sklo_l1";
			};
			
			class HitGlass6 : HitGlass1 {
				name = "sklo_l2";
				visual = "sklo_l3";
			};
			
			class HitGlass7 : HitGlass1 {
				name = "sklo_l3";
				visual = "glass3";
			};
			
			class HitGlass8 : HitGlass1 {
				name = "sklo_z";
				visual = "sklo_z";
			};
			
			class HitGlass9 : HitGlass1 {
				name = "sklo_pp";
				visual = "sklo_pp";
			};
			
			class HitGlass10 : HitGlass1 {
				name = "sklo_pl";
				visual = "sklo_pl";
			};
			
			class HitGlass11 : HitGlass1 {
				name = "sklo_p4";
				visual = "sklo_p4";
			};
			
			class HitGlass12 : HitGlass1 {
				name = "sklo_l4";
				visual = "sklo_l4";
			};
			
			class HitLFWheel {
				armor = 0.25;
				material = -1;
				name = "levy predni tlumic";
				visual = "";
				passThrough = 0.2;
			};
			
			class HitLBWheel : HitLFWheel {
				name = "levy zadni tlumic";
				visual = "";
			};
			
			class HitRFWheel : HitLFWheel {
				name = "pravy predni tlumic";
				visual = "";
			};
			
			class HitRBWheel : HitLFWheel {
				name = "pravy zadni tlumic";
				visual = "";
			};
			
			class HitLF2Wheel : HitLFWheel {
				name = "levy dalsi tlumic";
				visual = "";
			};
			
			class HitRF2Wheel : HitLFWheel {
				name = "pravy dalsi tlumic";
				visual = "";
			};
			
			class HitLMWheel : HitLFWheel {
				name = "levy prostredni tlumic";
				visual = "";
			};
			
			class HitRMWheel : HitLFWheel {
				name = "pravy prostredni tlumic";
				visual = "";
			};
		};
		hiddenSelections[] = {"Camo01"};
		hiddenSelectionsTextures[] = {"\kpfs_uaz451\civil\uaz451_lm.paa"};
	};
	
	class kpfs_uaz451_ff : kpfs_uaz451_lm {
		displayName = $STR_KPFS_UAZ451_FF;
		Icon = "\kpfs_uaz451\data\ico\icomap_van_ff_ca.paa";
		crew = "Assistant";
		hiddenSelections[] = {"Camo01"};
		hiddenSelectionsTextures[] = {"\kpfs_uaz451\civil\uaz451_ff.paa"};
	};
	
	class kpfs_uaz451_ambulance : kpfs_uaz451_lm {
		displayName = $STR_KPFS_UAZ451_AMB;
		Icon = "\kpfs_uaz451\data\ico\icomap_van_amb_ca.paa";
		crew = "Doctor";
		attendant = true;
		hiddenSelections[] = {"Camo01"};
		hiddenSelectionsTextures[] = {"\kpfs_uaz451\civil\uaz451_ambulance.paa"};
	};
};
