mklink /j "F:\arma 2 operation arrowhead\dayz"  "E:\projects\DayZUnleashed\SQF\dayz" 
mklink /j "F:\arma 2 operation arrowhead\dayz_anim" "E:\projects\DayZUnleashed\SQF\dayz_anim" 
mklink /j "F:\arma 2 operation arrowhead\dayz_equip" "E:\projects\DayZUnleashed\SQF\dayz_equip"
mklink /j "F:\arma 2 operation arrowhead\dayz_sfx" "E:\projects\DayZUnleashed\SQF\dayz_sfx"
mklink /j "F:\arma 2 operation arrowhead\dayz_weapons" "E:\projects\DayZUnleashed\SQF\dayz_weapons"
mklink /j "F:\arma 2 operation arrowhead\ew_wrecks_unleashed" "E:\projects\DayZUnleashed\SQF\ew_wrecks_unleashed"
mklink /j "F:\arma 2 operation arrowhead\HNG\addons\Dayz_Unleashed\activeLoot" "E:\projects\DayZUnleashed\SQF\activeLoot" 
mklink /j "F:\arma 2 operation arrowhead\z\addons\dayz_code" "E:\projects\DayZUnleashed\SQF\dayz_code" 
mklink /j "F:\arma 2 operation arrowhead\z\addons\dayz_communityassets" "E:\projects\DayZUnleashed\SQF\dayz_communityassets"
mklink /j "F:\arma 2 operation arrowhead\z\addons\dayz_server" "E:\projects\DayZUnleashed\SQF\dayz_server"
mklink /j "F:\arma 2 operation arrowhead\z\addons\unleashed_pack" "E:\projects\DayZUnleashed\SQF\unleashed_pack"

mklink /j "C:\arma 2 operation arrowhead client\dayz" "E:\projects\DayZUnleashed\SQF\dayz"
mklink /j "C:\arma 2 operation arrowhead client\dayz_anim" "E:\projects\DayZUnleashed\SQF\dayz_anim"
mklink /j "C:\arma 2 operation arrowhead client\dayz_equip" "E:\projects\DayZUnleashed\SQF\dayz_equip"
mklink /j "C:\arma 2 operation arrowhead client\dayz_sfx" "E:\projects\DayZUnleashed\SQF\dayz_sfx"
mklink /j "C:\arma 2 operation arrowhead client\dayz_weapons" "E:\projects\DayZUnleashed\SQF\dayz_weapons"
mklink /j "C:\arma 2 operation arrowhead client\ew_wrecks_unleashed" "E:\projects\DayZUnleashed\SQF\ew_wrecks_unleashed"
mklink /j "C:\arma 2 operation arrowhead client\HNG\addons\Dayz_Unleashed\activeLoot" "E:\projects\DayZUnleashed\SQF\activeLoot"
mklink /j "C:\arma 2 operation arrowhead client\z\addons\dayz_code" "E:\projects\DayZUnleashed\SQF\dayz_code"
mklink /j "C:\arma 2 operation arrowhead client\z\addons\dayz_communityassets" "E:\projects\DayZUnleashed\SQF\dayz_communityassets"
mklink /j "C:\arma 2 operation arrowhead client\z\addons\dayz_server" "E:\projects\DayZUnleashed\SQF\dayz_server"
mklink /j "C:\arma 2 operation arrowhead client\z\addons\unleashed_pack" "E:\projects\DayZUnleashed\SQF\unleashed_pack"