copy dayz_anim.pbo "D:\Program Files (x86)\Steam\SteamApps\common\ARMA 2 Operation Arrowhead\@DayZUnleashed\Addons"
copy dayz_code.pbo "D:\Program Files (x86)\Steam\SteamApps\common\ARMA 2 Operation Arrowhead\@DayZUnleashed\Addons"
copy dayz_communityassets.pbo "D:\Program Files (x86)\Steam\SteamApps\common\ARMA 2 Operation Arrowhead\@DayZUnleashed\Addons"
copy dayz_epoch.pbo "D:\Program Files (x86)\Steam\SteamApps\common\ARMA 2 Operation Arrowhead\@DayZUnleashed\Addons"
copy dayz_sfx.pbo "D:\Program Files (x86)\Steam\SteamApps\common\ARMA 2 Operation Arrowhead\@DayZUnleashed\Addons"
copy unleashed_pack.pbo "D:\Program Files (x86)\Steam\SteamApps\common\ARMA 2 Operation Arrowhead\@DayZUnleashed\Addons"
copy dayz.pbo "D:\Program Files (x86)\Steam\SteamApps\common\ARMA 2 Operation Arrowhead\@DayZUnleashed\Addons"
copy dayz_equip.pbo "D:\Program Files (x86)\Steam\SteamApps\common\ARMA 2 Operation Arrowhead\@DayZUnleashed\Addons"
copy dayz_vehicles.pbo "D:\Program Files (x86)\Steam\SteamApps\common\ARMA 2 Operation Arrowhead\@DayZUnleashed\Addons"
copy dayz_weapons.pbo "D:\Program Files (x86)\Steam\SteamApps\common\ARMA 2 Operation Arrowhead\@DayZUnleashed\Addons"

move dayz_anim.pbo "F:\arma 2 operation arrowhead\@DayZUnleashed\Addons"
move dayz_code.pbo "F:\arma 2 operation arrowhead\@DayZUnleashed\Addons"
move dayz_communityassets.pbo "F:\arma 2 operation arrowhead\@DayZUnleashed\Addons"
move dayz_epoch.pbo "F:\arma 2 operation arrowhead\@DayZUnleashed\Addons"
move dayz_sfx.pbo "F:\arma 2 operation arrowhead\@DayZUnleashed\Addons"
move unleashed_pack.pbo "F:\arma 2 operation arrowhead\@DayZUnleashed\Addons"
move dayz.pbo "F:\arma 2 operation arrowhead\@DayZUnleashed\Addons"
move dayz_equip.pbo "F:\arma 2 operation arrowhead\@DayZUnleashed\Addons"
move dayz_vehicles.pbo "F:\arma 2 operation arrowhead\@DayZUnleashed\Addons"
move dayz_weapons.pbo "F:\arma 2 operation arrowhead\@DayZUnleashed\Addons"
move dayz_server.pbo "F:\arma 2 operation arrowhead\@DayZUnleashedServer\addons"



move ..\..\DayZUnleashed_Hive\Hive\Binaries\HiveExt.dll "F:\arma 2 operation arrowhead\@DayZUnleashedServer"
move ..\..\DayZUnleashed_Hive\Hive\Binaries\DatabaseMySql.dll "F:\arma 2 operation arrowhead"